In [12]:
# Q1). Assign your Name to variable name and Age to variable age. Make a Python program that 
# prints your name and age.


name = "Manish"
age = 2 # Age is a hypothetical value for the language model

print("Name:", name)
print("Age:", age)

# Q2) X="Datascience is used to extract meaningful insights."
# Split the string

X = "Datascience is used to extract meaningful insights"
split_string = X.split()
print(split_string)


# Q3) Make a function that gives multiplication of two numbers

def multiply_numbers(a, b):
    return a * b
result = multiply_numbers(5, 3)
print(result)


# Q4) Create a Dictionary of 5 States with their capitals. also print the keys and values.

states_capitals = {
    'Bihar': 'Patna',
    'WestBengal': 'Kolkata',
    'Jharkhand': 'Ranchi',
    'Punjab': 'Chandigarh',
    'Goa': 'Panji'
}

# Print keys
print("States:")
for state in states_capitals.keys():
    print(state)

# Print values
print("Capitals:")
for capital in states_capitals.values():
    print(capital)

# Print both keys and values
print("States and Capitals:")
for state, capital in states_capitals.items():
    print(state, "-", capital)

# Q5) Create a list of 1000 numbers using range function.

numbers = list(range(1, 1001))
print(len(numbers))


# Q6)  Create an identity matrix of dimension 4 by 4


identity_matrix = [[1 if i == j else 0 for j in range(4)] for i in range(4)]
for row in identity_matrix:
    print(row)

# Q7). Create a 3x3 matrix with values ranging from 1 to 9

import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)

# Q8)Create 2 similar dimensional array and perform sum on them.

import numpy as np

# Create two similar-dimensional arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
result = array1 + array2

# Print the result
print(result)


# Q9)  Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

date_range = []
current_date = start_date

while current_date <= end_date:
    date_range.append(current_date)
    current_date += timedelta(days=1)

# Print the dates
for date in date_range:
    print(date.strftime("%Y-%m-%d"))

# Q10) Given a dictionary, convert it into corresponding dataframe and display it
# dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}


import pandas as pd

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(dictionary)

print(df)


Name: Prince
Age: 2
['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights']
15
States:
Bihar
WestBengal
Jharkhand
Punjab
Goa
Capitals:
Patna
Kolkata
Ranchi
Chandigarh
Panji
States and Capitals:
Bihar - Patna
WestBengal - Kolkata
Jharkhand - Ranchi
Punjab - Chandigarh
Goa - Panji
1000
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 8 10 12]
 [14 16 18]]
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01
     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
